### ISSUE TITLE
smafloatarraycreate,dgetrf,dgetri  are not included in the package

### ISSUE THREAD

**Issue by Summersyz** [InstituteOfMechanics/Thermomechanical_Gradient_Enhanced_Damage_UMAT#1]
When I tried to compile with Abaqus, the terminal prompted that "smafloatarraycreate", "dgetrf", and "dgetri" are missing.
The error like these:
UMAT_DamThermMech_1_H.obj : error LNK2019: Unresolved external symbol "smafloatarraycreate", function "umat_damage" referenced it.
UMAT_DamThermMech_1_H.obj : error LNK2019: Unresolved external symbol dgetrf, function umat_damage references this symbol.
UMAT_DamThermMech_1_H.obj : error LNK2019: Unresolved external symbol dgetri, function umat_damage references this symbol.
dear author,what i should do?

**Comment by InstituteOfMechanics** [comment]
Dear Summersyz,

thanks for your interest on our repository.

- "smafloatarraycreate" is an Abaqus internal "module". As mentioned in the repository description you need to store the "SMAAspUserArrays.hdr" - file (also available in the repository) into the folder where the User subroutine is placed (for example into the work directory).

- Both "dgetrf" and "dgetri" are lapack modules. They are required for the compilation of the code. You can easily find the "lapack"-package online and how to connect it to your Abaqus fortran compiler. 

I hope, that you should be able to compile the code based on these instructions. If you are not, please feel free to contact me again.

Best regards

**Comment by Summersyz** [comment]
> 亲爱的 Summersyz，
> 
> 感谢您对我们的存储库感兴趣。
> 
> * “smafloatarraycreate”是 Abaqus 内部“模块”。如仓库描述中所述，您需要将 “SMAAspUserArrays.hdr” - 文件（在仓库中也可用）存储到 User 子例程所在的文件夹中（例如，到工作目录中）。
> * “dgetrf” 和 “dgetri” 都是 lapack 模块。它们是编译代码所必需的。您可以在线轻松找到“lapack”软件包，以及如何将其连接到 Abaqus fortran 编译器。
> 
> 我希望，您应该能够根据这些说明编译代码。如果您不是，请随时再次与我联系。
> 
> 此致敬意

**Comment by Summersyz** [comment]
> Dear Summersyz,
> 
> thanks for your interest on our repository.
> 
> * "smafloatarraycreate" is an Abaqus internal "module". As mentioned in the repository description you need to store the "SMAAspUserArrays.hdr" - file (also available in the repository) into the folder where the User subroutine is placed (for example into the work directory).
> * Both "dgetrf" and "dgetri" are lapack modules. They are required for the compilation of the code. You can easily find the "lapack"-package online and how to connect it to your Abaqus fortran compiler.
> 
> I hope, that you should be able to compile the code based on these instructions. If you are not, please feel free to contact me again.
> 
> Best regards

ok,got it. Thank you for your warm and professional response.
