### ISSUE TITLE
The simulation results of the examples suggest  ZERO PIVOT  or NEGATIVE EIGENVALUES values, and some ANA value appears in the ODB file.

### ISSUE THREAD

**Issue by Summersyz** [InstituteOfMechanics/Thermomechanical_Gradient_Enhanced_Damage_UMAT#2]
Dear author,

When I tried to run the example and successfully ran it, the Abaqus message document prompted me with the following problem, and there are a lot of NAN values extracted from the ODB file. Is there something wrong with my operation? How can I solve these problems?
***WARNING: SOLVER PROBLEM.  ZERO PIVOT WHEN PROCESSING NODE 6 INSTANCE 
             PRIMARYINSTANCE D.O.F. 3
 ***WARNING: SOLVER PROBLEM.  ZERO PIVOT WHEN PROCESSING NODE 6 INSTANCE 
             PRIMARYINSTANCE D.O.F. 11
***WARNING: THE SYSTEM MATRIX HAS 52 NEGATIVE EIGENVALUES.

Best wishs

**Comment by InstituteOfMechanics** [comment]
Dear Summersyz,

I'm afraid this was our fault. We recently committed an update to the code that contained a bug. This bug caused the error you describe in your message.

Thank you very much for bringing this to our attention. We have just committed a fix. You should now be able to download the current version of the code and run the numerical examples.

If you still have problems with the code, please let us know.

Kind regards

**Comment by Summersyz** [comment]
Dear Author,

Now it can be successfully run and the results can be seen. 

Thank you for your excellent work, which has allowed our research to progress more quickly, and I also greatly admire your open-source spirit.

Best wishs

**Comment by InstituteOfMechanics** [comment]
Thanks for your feedback and all the best for your research.
Best regards
